### ISSUE TITLE
docker-compose is failing

### ISSUE THREAD

**Issue by Smahane** [singularityhub/sregistry#167]
**Describe the bug**
docker-compose fail to start the containers. This was working as of last Friday 11/09/2018
**To Reproduce**
docker-compose up -d

![image](https://user-images.githubusercontent.com/5471356/48369682-20720580-e66c-11e8-9c72-3a7b6296a0ed.png)

**Comment by vsoch** [comment]
I'm not sure what to say - nothing has changed for the code base or Docker image. I do not that golang was updated and apparently the hash versions are different (so possibly this is leading to not finding the one that are on record?) Are you having any other strange behavior? I'm not sure how to test or debug this because it seems like a Docker issue.

**Comment by Smahane** [comment]
I'm not sure either. The webpage was down. I tried to restart the containers and docker with no luck. The only other thing i see is that redis and postgres were created 2 days ago!

bash-4.4$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
redis                     latest              415381a6cb81        2 days ago          94.9MB
postgres                  latest              39dfbcb5424b        2 days ago          311MB
vanessa/sregistry_nginx   latest              c70438782655        2 weeks ago         193MB
vanessa/sregistry         latest              89cb0ad555f9        2 weeks ago         1.42GB

**Comment by vsoch** [comment]
The containers that are created from your image are local to your machine - so if they were recreated (as I can see in the graphic) it means that you must have stopped / removed them to warrant the re-creation. Also notice that the ones that are having issue are redis and postgres, not the nginx or worker image (two weeks ago). So again, the issue isn't with the sregistry image here but something with your containers. Can you share the exact commands you did since (all were up and running, the ones that were created two weeks ago) and now? Likely you interacted with the containers outside of docker-compose, so compose (and the internal networking) has the previous (now removed) containers gone, and can't find them so it's giving you issue. In the future, whenever you have containers running with docker compare you have to be so careful to keept them in sync, and never stop / remove or change one if there is risk of corrupting the other.

**Comment by vsoch** [comment]
I think you are having an issue like this: https://stackoverflow.com/questions/37454548/docker-compose-no-such-image and would need to remove old image (that are cached) and create again.

**Comment by vsoch** [comment]
Ah, also looks like redis 5 was released recently? https://github.com/docker-library/redis/blob/master/5.0/Dockerfile So if you are recreating (and asking for latest) and the docker-compose has a different "latest" in the cache, it's not going to find the new one.

**Comment by Smahane** [comment]
I had the exact issue as was described in the link you posted above.  Thank you very much. The containers are up and running now.

**Comment by vsoch** [comment]
Woohoo! Definitely just bad luck I think - especially with the update to redis and OCI different hashing on top of it all. Happy container-ing!
