### ISSUE TITLE
LDAP Login Option

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#2]
From a user:

>> Our authorization for other systems is entirely built around LDAP whenever possible. I think that's quite common for HPC.

>> InfoSec etc. really want to know how authorization is maintained for different systems - and management at a central LDAP directory using LDAP groups makes that much more straightforward to keep an eye on, and document

>> The email uniqueness thing goes like this - 'Researcher A works in a lab, but also in a core facility. They only have one email address but 2 separate accounts on the HPC system. This is so that their work/data between core and lab can be separated' - so we have many people with 2 usernames sharing same email - and they use our various systems with the 2 different usernames for different work that needs to be separated.

**Comment by dctrud** [comment]
I've forked the repo - will see if I can sort out an LDAP auth PR by middle of next week.

**Comment by vsoch** [comment]
Gitlab added!

![image](https://user-images.githubusercontent.com/814322/29475010-0f65548e-842c-11e7-8e91-807acc0b8cba.png)

**Comment by dctrud** [comment]
Awesome. Thanks!

**Comment by deardooley** [comment]
Any chance for generic OAuth2 support? I'd like to integrate this with our existing platform auth server.

**Comment by vsoch** [comment]
Yep, the login / user management (separate from API tokens / auth) is done by way of python social auth - https://python-social-auth.readthedocs.io/en/latest/backends/index.html and I've implemented the standard social platforms along with now Gitlab, Github, and SAML. If you'd like one added, I'd be happy to do so.

**Comment by sysmso** [comment]
Hello
What about the LDAP Login Option ? We really need this to use sregistry in our laboratory.
Thanks

**Comment by dctrud** [comment]
This is back on my radar - we need LDAP in the end as our GitLab includes some extra external accounts that we don't want to have registry access. I've just managed to get back to a saner schedule, so may be able to do an LDAP auth PR soon. Will start having a look tonight.

**Comment by vsoch** [comment]
Excellent! @akkornel was doing a bit of work with python and LDAP and might be able to weight in.

**Comment by dctrud** [comment]
Great - @akkornel, do you have any existing stuff related to sregistry, or was this other Python code? I have a lot of Django apps here authenticating against LDAP so just need to work out how to fit in neatly with the sregistry structure / config files.

**Comment by vsoch** [comment]
The simplest idea is to just have a boolean in the config (akin to the other login options) that the admin can set to True or False, and then any supplementary variables that are needed, with instructions written up in the deployment/install page docs!  But maybe we should think a bit more about this - arguably a plugin would be like a django app, no? If it's a substantial amount of code and relatively modular, having it's own app (under the apps folder) might make sense, and then the user adds to "installed_apps." I think that's the way Django is intended to be, although I don't follow it so well, heh.

**Comment by dctrud** [comment]
It shouldn't be a lot of code. Really just config settings and minimal code to make sure django_auth_ldap can be loaded and used as an AUTHENTICATION_BACKEND properly. I'll try and mock up something that makes sense to me, and then

**Comment by vsoch** [comment]
Here might be a good place to start, you can basically just mimic any of the other (gazillion) backends to plug into what you know about LDAP:

https://python-social-auth.readthedocs.io/en/latest/backends/index.html#adding-new-backend-support

**Comment by akkornel** [comment]
If you can use django_auth_ldap, then that would be good.  Otherwise, the basic process is this:

• You get a set a credentials from the LDAP admin (a bind DN and password), which gives you access to query whatever part of the LDAP tree has user info.  So you'll have a bind DN, password, a search base (like `ou=People,dc=example,dc=com`, a search scope (typically `sub`), and the name of the attribute which holds the username (typically `uid`).
• When a person logs in, you use your LDAP credentials to search for that username.  When found, you get the Distinguished Name of the user's LDAP record, and then disconnect.  You then reconnect to the LDAP server, authenticating with the Distinguished Name, and the password the user provided on login.  If those credentials work, then the user is authenticated.

Other attributes you'll want are typically their name (normally `displayName`), email address (`mail`), and the attribute which lists the groups they're a member of (`memberOf`).

But, this won't be an end-all solution.  For example, it wouldn't work at Stanford, because our LDAP spreads that out in multiple places.  We also don't like sending passwords over the network.  So for us, we'd use either SAML, or Login With Gitlab, or Login With Google.

**Comment by vsoch** [comment]
Thanks @akkornel! I've implemented SAML with social auth before so arguably that could be a plugin too. @dctrud works in a high security (top secret!) center and likely has very specific needs for LDAP. The good news I think is that we can easily accommodate most of these use cases.

**Comment by vsoch** [comment]
woohoo @dctrud it's merged!! Closing... great job!
