### ISSUE TITLE
Error while validating (valid) token

### ISSUE THREAD

**Issue by RonaldEnsing** [singularityhub/sregistry#247]
I run into an issue with token validation. Whenever I do `singularity remote login myserver` I simply copy the token from `<myserver>/token`. This results in `FATAL: while verifying token: error response from server: Invalid Token`. If I check the status with `singularity remote status myserver`, I get the following:
```
SERVICE           STATUS  VERSION
Keystore Service  OK      v1.0.0
Library Service   OK      v1.0.0
Token Service     OK      v1.0.0
```
I am using commit `1dc800b8eff66013df59a80c1801847874e11341` of sregistry and singularity v3.3.0 (installed from source) on ubuntu 18.04. Any idea what could be causing this?

**Comment by vsoch** [comment]
I ran into this issue too - and I need to debug it further. The quick workaround is to open up the remote.yml file in your $HOME (mine is at /home/vanessa/.singularity/remote.yaml ) and then just enter the token directly. This happened to me before and I documented this here https://singularityhub.github.io/sregistry/docs/client. But after just changing the token string, it seems to work ok:

```
$ singularity push -U tiny-container_tiny.sif library://vsoch/dinosaur-collection/tiny:tag
WARNING: Skipping container verifying
INFO:    http://127.0.0.1
INFO:    ff4a371320ad839e54cd2cc27a4ce861688f8e7a
INFO:    library://vsoch/dinosaur-collection/tiny:tag
INFO:    [tag]
 764.00 KiB / 764.00 KiB [==============================] 100.00% 26.35 MiB/s 0s
(base) vanessa@vanessa-ThinkPad-T460s:~/Documents/Dropbox/Code/sregistry/server$
```
This did work for me the very first time I did it, so I suspect something changed in the response that I need to look into further! I'll add this to my TODO for when I can make some time - I'm moving cross country this week and next, plus SC, and regular work, so I have quite a bit to do!

**Comment by RonaldEnsing** [comment]
Thanks a lot for your quick response and suggested workaround. I will give that a try.

**Comment by vsoch** [comment]
hey @RonaldEnsing I have a fix for you!

https://github.com/singularityhub/sregistry/pull/251

The issue turned out to be rather silly, and actually I'm not sure why it would behave differently between different timepoints (maybe the client had different capitalization for Bearer?) Basically, I parsed the token header by replacing BEARER with nothing, but the requests coming in now use Bearer. Since we can be sure it's some version of bearer, a space, and then the token, a clean fix is to split the string by whitespace, and take the second half (the token). Take a look at the PR, let me know if it works for you, and we'll get this fix in.

**Comment by RonaldEnsing** [comment]
Yes, this works for me. I've tested this and it works.

**Comment by vsoch** [comment]
Great! I'll merge the PR.
