### ISSUE TITLE
Running behind reverse proxy

### ISSUE THREAD

**Issue by snu-ceyda** [singularityhub/sregistry#276]
I already have several applications on my server so I'm trying to run the registry behind a reverse proxy. 
I map the docker nginx container port [myport]:80 and run another simple proxy doing sregistry.domain -> localhost:[myport]
I run sregistry in http mode and let my proxy handle the https stuff.
The web interface works as expected...all good 👍 

**But** I cannot do "singularity pull/push" (or "sregistry pull/push")
I have modified remote.yaml with my token according to the docs but everything returns forbidden. 
I can see the requests coming to the sregistry (docker-compose logs -f)
but returns "403 forbidden" (even singularity remote status, and even singularity remote login Forbidden: /v1/token-status)
at first I was using `DOMAIN_NAME='https://my.domain.etc'` but suspecting that this maybe some CORS related issue(?) I tried the following:

So i figured out that the singularity cli gets the registry api endpoints from the file `/shub/apps/base/templates/assets/config.prod.json` which gets the domain name from the `config.py`

I set the DOMAIN_NAME to http://127.0.0.1 in config.py (since sregistry doesn't know it is running behind a reverse proxy on my.domain.etc) and edited the 
`config.prod.json` to have my.domain.etc (instead of localhost) so that the singularity cli can send the requests to the correct api endpoints.

But I'm still getting forbidden, what can be going wrong?
how can put uwsgi or nginx  in debug mode so that i can see the request headers being passed in the logs. this is all i can see right now:
![image](https://user-images.githubusercontent.com/15624271/75854069-ab16df00-5e32-11ea-8de9-35cc2315e8a6.png)

Some more of my other configs:
-This is a private registry
-USER_COLLECTIONS= true (i'm trying as the admin user anyway)

singularity version 3.5.2
GET registry.domain/version returns
version : "v1.0.0"
apiVersion : "2.0.0-alpha.1"

**Comment by vsoch** [comment]
I'd first verify that it's not [this issue](https://github.com/singularityhub/sregistry/issues/247) (likely not if you are using a recent clone) and then also for a sanity check, try a version of Singularity in the 3.2.x family. I can't keep up with the changes that they do to the API and client (that they do not share publicly) so we should rule out those changes first. To see logs for nginx, you would just do:
```
docker-compose logs --tail=30 nginx
```
I'm concerned that you aren't hitting the endpoint at all because if you look at the [functions](https://github.com/singularityhub/sregistry/blob/a6b0c0d9d9ac67d240ebc295ef610af96d3e84fc/shub/apps/library/views/auth.py) for the view, I don't see any 400 (Forbidden) responses. As a next check, try adding a print statement to the function [here](https://github.com/singularityhub/sregistry/blob/a6b0c0d9d9ac67d240ebc295ef610af96d3e84fc/shub/apps/library/views/auth.py#L25) to tell you what's going on, and see if it appears in the logs. If not, this tells us it's something about your proxy setup. After that we need to look into cases of proxy setups returning general 400 Forbiddens on views.

Also, if you aren't aware of the [nginx.conf](https://github.com/singularityhub/sregistry/blob/master/nginx.conf) I think you might need to adjust rules there as well.

**Comment by snu-ceyda** [comment]
Good news~
Thanks for your suggestions, I had already tried some of them and hadn't found anything wrong.
At the end the problem turned out to be that I had 
[this line](https://github.com/singularityhub/sregistry/blob/f23ca2c5fd0cf381f8f687131212e25f102d251e/shub/settings/api.py#L15) uncommented. I must have done that a while back for security (?)

What is the proper use/setup of the DEFAULT_PERMISSION_CLASSES anyway?

**Comment by vsoch** [comment]
Wonderful! I'm so glad that you caught that, it would have taken me a long time to figure out where the message was coming from and think of drf. SIngularity Registry Server uses the Django Rest Framework, and using this config that you found you can set permissions globally across endpoints (see docs here https://www.django-rest-framework.org/api-guide/permissions/). I have this disabled because it's really up to the registry to decide how they want to do this.  If you look at the functions you'll generally notice that we implement [rate limiting](https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L57) (there is also a setting for limits in the settings)  , and the containers themselves have a weekly GET limit since someone can pull without using a token (see [here](https://github.com/singularityhub/sregistry/blob/master/shub/apps/main/models/containers.py#L85)). And instead of using django restful authentication, we use a user generated token with the sylabs api. 

So - default permission classes assume you want to control access globally using drf, which by default is disabled for the reasons above. But you are free to change this however you need for your registry!

**Comment by snu-ceyda** [comment]
Thanks, I'm closing this issue
