### ISSUE TITLE
Is DATA_UPLOAD_MAX_MEMORY_SIZE actually used?

### ISSUE THREAD

**Issue by Aneoshun** [singularityhub/sregistry#290]
Hi !

I have been using SRegistry on my Synology NAS without issue for a couple of months now, and that's really great. 
However, I am starting to manipulate significantly larger containers (about 3GB, while so far I used 700MB). My NAS has only 2GB of RAM (yeah... I should definitely increase it, but in lockdown condition, it's, for now, impossible), and the push of my large containers fails with a 403 error (in addition to perturbing the other services running on the NAS). The 403 error received from the client, but the SRegistry logs show things like this: 
```
[error] 6#6: *3392 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "PUT /v2/push/imagefile/261/SHA_REDACTED HTTP/1.1", upstream: "uwsgi://172.17.0.4:3031", host: "REDACTED" 
```

In `config.py`, I set `DATA_UPLOAD_MAX_MEMORY_SIZE = 500`, but it does not seem to help. 

When I use the search bar in GitHub, DATA_UPLOAD_MAX_MEMORY_SIZE seems to appear only once on the repo (in the config.py). So, I am wondering if this setting is actually used and whether there is a way to improve the situation on my side?

Note: copying the same containers on the same NAS via NFS works without issue, so it is not a network capability issue. 

I will be very glad if you have a suggestion on this. 

Thanks a lot in advance. 

Best regards and stay safe!

**Comment by vsoch** [comment]
hey @Aneoshun ! I've had this issue as well, and it's always when I'm low on memory, and I can tell because my computer starts to freeze up during upload of some large container. It shows up in different ways (sometimes I see an EOF) but the fix is always clearing up memory. I don't have a quick fix solution because singularity handles the logic of the upload, but generally I'd recommend deploying the registry on a host that has maybe at least 8GB. The computer I am on now (that has 16GB) can even have issues with large container pushes when memory is running low.

For the field, it's actually a Django default https://docs.djangoproject.com/en/3.0/ref/settings/#data-upload-max-memory-size setting, and it's only relevant for GET or POST. What you could try is to set the https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-FILE_UPLOAD_MAX_MEMORY_SIZE. Actually, since this is what we are now doing with the new API endpoint, I think this might be the fix! Do you want to try setting that, report back, and let me know if it helps? If it does we can add it to the default settings.

**Comment by vsoch** [comment]
Also, make sure that you are using the correct units! 

```
Default: 2621440 (i.e. 2.5 MB).
```
so if you set it to 500, I think 500 bytes is only 0.0005 MB.

**Comment by vsoch** [comment]
hey @Aneoshun I looked at config.py and the default is poorly chosen *and* the link to the docs is missing, and the units specified is incorrect! Please try out these changes https://github.com/singularityhub/sregistry/pull/291 and let me know if they work! If so, we can merge and hopefully others will avoid this problem.

**Comment by Aneoshun** [comment]
I am testing your PR, but it will take some time before I can report back as each test take dozens of minutes.  More soon.

**Comment by vsoch** [comment]
Totally okay! I promise I'll still be around when you are ready. :)

**Comment by Aneoshun** [comment]
Alright, conclusion: I cannot see a difference. I pulled your PR, recompile the docker images, restarted the docker-compose (did I miss something?) and the memory still goes to 95% and the upload fails. 

If it is the singularity client that manages the logic of the upload, would using the SRegistry client be a possible solution?

Thanks again for your prompt reponse!

**Comment by vsoch** [comment]
Did you try setting `DATA_UPLOAD_MAX_MEMORY_SIZE` to None, and `FILE_UPLOAD_MAX_MEMORY_SIZE` to something huge? The default would still be very small (2.5MB).

**Comment by Aneoshun** [comment]
Ah! I misinterpreted the doc, sorry. Indeed setting DATA_UPLOAD_MAX_MEMORY_SIZE to None could help as it will remove the check which can take a lot of memory.  I have now set FILE_UPLOAD_MAX_MEMORY_SIZE to 250MB and DATA_UPLOAD_MAX_MEMORY_SIZE to None.

Unfortunately, I still see the same behaviour, even tho it takes less time to crash.  

Am I correct to think that I don't have to rebuild the container if the only difference is the config.py, and that a simple restart of docker-compose would work?

**Comment by Aneoshun** [comment]
By the way, the description in `config.py` seems confusing to me. From my understanding of [the doc](https://docs.djangoproject.com/en/3.0/ref/settings/#data-upload-max-memory-size), `DATA_UPLOAD_MAX_MEMORY_SIZE` will trigger a sanity check on the data to prevent DDos, but is not directly related to streaming to the filesystem (conversely to what `config.py` says).

**Comment by vsoch** [comment]
Sorry just need to check again - if you want 250MB you would need to specify that in bytes, you'd need 250000000 (I think that is correct). My understanding is that the `DATA_MAX_MEMORY_SIZE` sets the limit on what size POST/GET request bodies are stores in memory. If the content size is larger than that, it switches to the file system. It's sort of like a handoff.

**Comment by Aneoshun** [comment]
Yes, I used `FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000` (I took the default 2.5MB and multiplied the value by 100 ^^). 

What you describe is what I understand for `FILE_UPLOAD_MAX_MEMORY_SIZE`, but not for `DATA_MAX_MEMORY_SIZE`
 
The doc says: 
```
The maximum size in bytes that a request body may be before a SuspiciousOperation (RequestDataTooBig) is raised. The check is done when accessing request.body or request.POST and is calculated against the total request size excluding any file upload data. You can set this to None to disable the check. Applications that are expected to receive unusually large form posts should tune this setting.

The amount of request data is correlated to the amount of memory needed to process the request and populate the GET and POST dictionaries. Large requests could be used as a denial-of-service attack vector if left unchecked. Since web servers don’t typically perform deep request inspection, it’s not possible to perform a similar check at that level.
```

Could it be that `data` is never streamed to the filesystem, while `file` can be depending on  `FILE_UPLOAD_MAX_MEMORY_SIZE`?

**Comment by vsoch** [comment]
Yeah you're correct! I think this is why I set the default to None (so it's skipped, because containers are huge). So - did you set this to `None` and then make the `FILE_UPLOAD_MAX_MEMORY_SIZE` something very large? If so, then probably there isn't much you can do, aside from having a larger host for your registry.

**Comment by Aneoshun** [comment]
Yes, I used the following: 
```
# Set this to be some size in bytes to limit uploads.
# Uploads > 2.5GB will not use memory, but the filesystem
# https://docs.djangoproject.com/en/3.0/ref/settings/#data-upload-max-memory-size
DATA_UPLOAD_MAX_MEMORY_SIZE = None

# The same is the case for streaming to the filesystem
# https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-FILE_UPLOAD_MAX_MEMORY_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000
```
My rationale is that if the container is larger than 250MB, I want it to be directly stored on the filesystem and not on the RAM. Setting this value to something larger than my available RAM will make the situation worse from my understanding.

**Comment by vsoch** [comment]
The container is always stored on the file system - the failure is because we have to stream it there (from memory). You are running out of memory.

**Comment by vsoch** [comment]
Can you test on a host with more memory?

**Comment by Aneoshun** [comment]
Hi @vsoch,

Sorry for the delay, I needed some time to wrap my head around this issue and it is now a lot clearer to me. I do understand now that the message is received in one shot (or as a stream) and stored in the memory before being streamed on the filesystem (and then moved at the right location). 

From my reading the SRegistry code, your [blog post on django-nginx chunked upload ](https://vsoch.github.io/2018/django-nginx-upload/), and the SCS client library, I can suppose that there is maybe a way to do a multi-chunk upload, where each chunk is systematically saved on the file system and not stored in memory, which would solve my problem. 
It seems by the way that the singularity client just added this feature on the latest version, which required you to add a 404 page on the upload views. There is maybe a way to implement this also on the server-side, but this is borderline to my knowledge. 

Also, I had a question while reading the SRegistry code, the `OctetStreamParser` implements a sort of multi-chunk reading and storing, but the minimum size of the chunks seems to be 2GB:
https://github.com/singularityhub/sregistry/blob/f8530b98b94dbed250114ea3f0940c6061ba1a88/shub/apps/library/views/parsers.py#L80

Is that normal?

I am sure there are a ton of subtilities that I did not get, as most of these concepts are new to me, so I expect some misunderstandings. 

Finding a host with more ram is difficult as I am doing everything remotely, and I don't have a potential host (except those in production...) to do such a test at the moment, but I will try to find an alternative in the new few days.

**Comment by vsoch** [comment]
hey @Aneoshun ! The django-nginx chunked upload was the implementation I did for an upload with the sregistry client. For the Sylabs client, I can't use the same flow, so it's a stream to the filesystem as you noted. 

The chunk size for reading the upload I don't think would be salient to change about 2GB, that's just the [size of the piece](https://github.com/singularityhub/sregistry/blob/f8530b98b94dbed250114ea3f0940c6061ba1a88/shub/apps/library/views/parsers.py#L91) that is read in at each time.

I do think that since Sylabs has recently added the multi part endpoint, it might be possible to implement for sregistry, but honestly I've spent so much time on this file upload bit (maybe you can tell from my post?) that I'm out of ideas. How is it implemented?

One idea that I had, actually with a different use case, would be to [return the URL here](https://github.com/singularityhub/sregistry/blob/3a254feabdf19b6ec6df3281b2a6e767684051e0/shub/apps/library/views/images.py#L126) to push to for some kind of cloud storage, that way the interaction with the local client and storage would not burden the server. And then to pull, a signed URL from storage would be returned (this is how the Google Build plugin is implemented). I like this idea because it takes burden off of the server for storing the images, but also I'm aware many "super private" centers aren't wanting to use the cloud. Anyway, for the idea, my thinking is that the URL returned could be the same upload point for nginx, but I don't think this is the most secure approach (and it would be challenging to implement). Does the push work for you with sregistry / upload from the browser? That would be the first test to see if it's worth trying, period.

**Comment by Aneoshun** [comment]
> hey @Aneoshun ! The django-nginx chunked upload was the implementation I did for an upload with the sregistry client. For the Sylabs client, I can't use the same flow, so it's a stream to the filesystem as you noted.
> 
Would it be interesting for me to test the sregistry client? Happy to test it!

> The chunk size for reading the upload I don't think would be salient to change about 2GB, that's just the [size of the piece](https://github.com/singularityhub/sregistry/blob/f8530b98b94dbed250114ea3f0940c6061ba1a88/shub/apps/library/views/parsers.py#L91) that is read in at each time.

Not sure to see what you mean, but ok. 

> 
> I do think that since Sylabs has recently added the multi part endpoint, it might be possible to implement for sregistry, but honestly I've spent so much time on this file upload bit (maybe you can tell from my post?) that I'm out of ideas. How is it implemented?

The implementation is [here](https://github.com/sylabs/scs-library-client/blob/5d0614e4bddff1b2231efe79609f9f177bec8014/client/push.go#L298)
and seems designed to work with S3.

From my understnading, the transfer is initiated with a POST request to get the following from the server
response.UploadID, 
response.TotalParts # number of parts
response.PartSize

So the number of parts and their size is driven by the server, which seems quite good. 
Then, there is a for loop over the chunks, each of them being sent via PUT, also including:
PartSize
UploadID
PartNumber
SHA256Checksum

Finally, the client sends a CompleteMultipartUploadRequest to notify completion. There is also a view to abort the upload.

> 
> One idea that I had, actually with a different use case, would be to [return the URL here](https://github.com/singularityhub/sregistry/blob/3a254feabdf19b6ec6df3281b2a6e767684051e0/shub/apps/library/views/images.py#L126) to push to for some kind of cloud storage, that way the interaction with the local client and storage would not burden the server. And then to pull, a signed URL from storage would be returned (this is how the Google Build plugin is implemented). I like this idea because it takes burden off of the server for storing the images, but also I'm aware many "super private" centers aren't wanting to use the cloud. Anyway, for the idea, my thinking is that the URL returned could be the same upload point for nginx, but I don't think this is the most secure approach (and it would be challenging to implement). Does the push work for you with sregistry / upload from the browser? That would be the first test to see if it's worth trying, period.

On my use case, the storage server is the same as the host server, so that won't be helping in my case. It's not about being super private in my case, but more to be very local so that I can exchange large images in a couple of seconds. 

I tried the UI upload and it behave differently. The memory usage increases linearly with the time, instead of being filled instantaneously. However, I haven't tried with a very large image, and I tried with limited internet connection, so that a lot of different factors. I will try to do proper tests soon.

**Comment by vsoch** [comment]
@Aneoshun I started testing this out, it looks like their client doesn't send a Content-Type header for the multipart post (which is weird, tbh, it's usually required and is considered best practice):
```
nginx_1      | 172.17.0.1 - - [01/Apr/2020:18:09:09 +0000] "GET /version HTTP/1.1" 200 58 "-" "Go-http-client/1.1" "-"
nginx_1      | 2020/04/01 18:09:10 [error] 6#6: *1 missing Content-Type header, client: 172.17.0.1, server: localhost, request: "POST /v2/imagefile/10/_multipart HTTP/1.1", host: "127.0.0.1"
nginx_1      | 172.17.0.1 - - [01/Apr/2020:18:09:10 +0000] "POST /v2/imagefile/10/_multipart HTTP/1.1" 400 173 "-" "Go-http-client/1.1" "-"
```
I'm not great with nginx, but I was unable to set it

```
  # Upload for Sylabs Library API
  location ~ ^/v2/imagefile/(?<imageid>[0-9]+)/_multipart {

        add_header Content-Type "application/octet-stream";

        # Pass altered request body to this location
        upload_pass   /api/uploads/complete/;

        # Store files to this directory
        # The directory is hashed, subdirectories 0 1 2 3 4 5 6 7 8 9 should exist
        upload_store /var/www/images/_upload 1;        
        upload_store_access user:rw group:rw all:rw;

        # Set specified fields in request body
        upload_set_form_field $upload_field_name.name "$upload_file_name";
        upload_set_form_field $upload_field_name.content_type "$upload_content_type";
        upload_set_form_field $upload_field_name.path "$upload_tmp_path";

        # Inform backend about hash and size of a file
        upload_aggregate_form_field "$upload_field_name.md5" "$upload_file_md5";
        upload_aggregate_form_field "$upload_field_name.size" "$upload_file_size";

        upload_pass_form_field "^submit$|^description$";
        upload_pass_form_field "^imageid$";
        upload_cleanup 400-599;

    }
```
When I do the same kind of nginx upload with sregistry, I set it explicitly
```
    headers = {"Content-Type": monitor.content_type, "Authorization": SREGISTRY_EVENT}

    try:
        r = requests.post(url, data=monitor, headers=headers)
        r.raise_for_status()
        message = r.json()["message"]
        print("\n[Return status {0} {1}]".format(r.status_code, message))
    except requests.HTTPError as e:
        print("\nUpload failed: {0}.".format(e))
    except KeyboardInterrupt:
        print("\nUpload cancelled.")
```

**Comment by vsoch** [comment]
> From my understnading, the transfer is initiated with a POST request to get the following from the server

The issue with using nginx upload is that the request hits the server _first_ so we have to process the file directly with nginx, and it gets saved to the filesystem. Then there is an equivalent "complete" view that is called that would allow for the server to get the image id, and finish up (e.g., moving the file, saving collection, etc.) This would also be where these responses are sent back:

```
response.UploadID,
response.TotalParts # number of parts
response.PartSize
```
It seems there are a few options here:
 - figure out how to get nginx to receive the initial post (doesn't seem to be working without content type)
 - implement a remote storage (GCP, etc.) which doesn't seem to help your use case
 - Some other multipart upload implementation that I'm not sure what would come down to (I need at least some kind of working example, I can't pull these things out of my head).

**Comment by vsoch** [comment]
> I tried the UI upload and it behave differently. The memory usage increases linearly with the time, instead of being filled instantaneously. However, I haven't tried with a very large image, and I tried with limited internet connection, so that a lot of different factors. I will try to do proper tests soon.

This is the nginx upload that I described above, although through the browser. The nginx upload from the command line is the same thing, but just without the browser (maybe greater limits on memory). I suggested you try both because getting the first point working in my previous comment would come down to using nginx to upload.

**Comment by vsoch** [comment]
If nginx upload doesn't work because of the Content Type header missing, the next thing we could try is to create this multi part upload endpoint, and just try to figure out how sylabs is trying to interact with it. The goal would be to figure out how data is being sent, and then how to handle open / close of a stream to file (and then finish of it's parsing).

**Comment by vsoch** [comment]
hey @Aneoshun I just got an idea that I think might work! What if we tried adding the [ceph/minio](https://singularityhub.github.io/sregistry-cli/client-swift) backend to sregistry? As far as I know you can deploy it locally, and since it's an object storage it should be able to handle more bulk / larger pull /push. The link there is just for a little sregistry client, so what we would do is modify it to be a container in the docker-compose and then add it as a plugin to hook in to the already existing push and pull. Let me know what you think.

**Comment by vsoch** [comment]
Hey @Aneoshun sorry for poking you so many times! I implemented my idea for Minio https://github.com/singularityhub/sregistry/pull/297 and I think it's a really promising solution - Minio is essentially like S3 so it plugs nicely into the Singularity client, and it adds signed URLS for GET and POST (download and upload) of containers, which is much better than the current approach with nginx. It also moves the burden of handling upload/download off of the sregistry server, and I would imagine that minio can be more easily scaled. And for your purposes, you can deploy your own Minio storage easily (for the PR linked above it's an added container, but you could easily change this to be some scaled version with a different URL). Give it a try, let me know what you think! I added the next set of TODOs in the PR - namely figuring our how to bind certificates for SSL, etc.

**Comment by Aneoshun** [comment]
Hi @vsoch, Don't be sorry for poking me, I am very happy to see that you have an idea that could solve my problem. I have been very busy in the last few days, I will try the PR asap!

**Comment by vsoch** [comment]
hey @Aneoshun another update for you - I've finished multipart upload so it's implemented to work with the Sylabs scs-library-client through Singularity, you should be able to try this out https://github.com/singularityhub/sregistry/pull/298.

After trying the basics, what we need to work on (and write docs for) is how to change the default username / password for Minio, and then the minimal steps needed to set up SSL for minio. Other than that, this is a fully working thing for http (MINIO_SSL=False).

**Comment by Aneoshun** [comment]
Fantastic! I am looking forward to testing this. It's in my todo list, which unfortunately is way longer than usual... ><

**Comment by vsoch** [comment]
Totally ok :) Whenever you are able, I’m looking forward to it! I’ll start reading up on how to do SSL too.

**Comment by Aneoshun** [comment]
I don't think I will be able to help on the SSL side, as I did not even try to set it up with the master branch.

**Comment by vsoch** [comment]
@Aneoshun just to confirm - this is not needed anymore?

**Comment by Aneoshun** [comment]
Yes. This issue is solved with the MinIO backend. Thanks!
